version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: salesduo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - '4000:4000'
    links:
      - db

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  db_data:
